/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLabRouteImport } from './routes/_app.lab'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppHospitalsRouteImport } from './routes/_app.hospitals'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'
import { Route as AppStaffIndexRouteImport } from './routes/_app.staff.index'
import { Route as AppPharmacyIndexRouteImport } from './routes/_app.pharmacy.index'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppLabIndexRouteImport } from './routes/_app.lab.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppHospitalsIndexRouteImport } from './routes/_app.hospitals.index'
import { Route as AppDoctorsIndexRouteImport } from './routes/_app.doctors.index'
import { Route as AppBillingIndexRouteImport } from './routes/_app.billing.index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app.appointments.index'
import { Route as AppAdmissionsIndexRouteImport } from './routes/_app.admissions.index'
import { Route as AppStaffScheduleRouteImport } from './routes/_app.staff.schedule'
import { Route as AppStaffPayrollRouteImport } from './routes/_app.staff.payroll'
import { Route as AppStaffLeavesRouteImport } from './routes/_app.staff.leaves'
import { Route as AppStaffCreateRouteImport } from './routes/_app.staff.create'
import { Route as AppStaffAttendanceRouteImport } from './routes/_app.staff.attendance'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppPharmacyPurchasesRouteImport } from './routes/_app.pharmacy.purchases'
import { Route as AppPharmacyDispenseRouteImport } from './routes/_app.pharmacy.dispense'
import { Route as AppPatientsIdRouteImport } from './routes/_app.patients_.$id'
import { Route as AppPatientsRegistrationRouteImport } from './routes/_app.patients.registration'
import { Route as AppLabSamplesRouteImport } from './routes/_app.lab.samples'
import { Route as AppLabResultsRouteImport } from './routes/_app.lab.results'
import { Route as AppInventoryPurchasesRouteImport } from './routes/_app.inventory.purchases'
import { Route as AppHospitalsIdRouteImport } from './routes/_app.hospitals_.$id'
import { Route as AppHospitalsDepartmentsRouteImport } from './routes/_app.hospitals.departments'
import { Route as AppHospitalsBedsRouteImport } from './routes/_app.hospitals.beds'
import { Route as AppDoctorsAvailabilityRouteImport } from './routes/_app.doctors.availability'
import { Route as AppDoctorsAssignmentsRouteImport } from './routes/_app.doctors.assignments'
import { Route as AppBillingIdRouteImport } from './routes/_app.billing_.$id'
import { Route as AppBillingPaymentsRouteImport } from './routes/_app.billing.payments'
import { Route as AppAppointmentsBookingRouteImport } from './routes/_app.appointments.booking'
import { Route as AppAdmissionsDischargeRouteImport } from './routes/_app.admissions.discharge'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppPharmacyIndexRoute = AppPharmacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppLabIndexRoute = AppLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLabRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHospitalsIndexRoute = AppHospitalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHospitalsRoute,
} as any)
const AppDoctorsIndexRoute = AppDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDoctorsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAdmissionsIndexRoute = AppAdmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdmissionsRoute,
} as any)
const AppStaffScheduleRoute = AppStaffScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffPayrollRoute = AppStaffPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffLeavesRoute = AppStaffLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffCreateRoute = AppStaffCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppStaffAttendanceRoute = AppStaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppStaffRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPharmacyPurchasesRoute = AppPharmacyPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPharmacyDispenseRoute = AppPharmacyDispenseRouteImport.update({
  id: '/dispense',
  path: '/dispense',
  getParentRoute: () => AppPharmacyRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/patients_/$id',
  path: '/patients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRegistrationRoute = AppPatientsRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppLabSamplesRoute = AppLabSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AppLabRoute,
} as any)
const AppLabResultsRoute = AppLabResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppLabRoute,
} as any)
const AppInventoryPurchasesRoute = AppInventoryPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHospitalsIdRoute = AppHospitalsIdRouteImport.update({
  id: '/hospitals_/$id',
  path: '/hospitals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsDepartmentsRoute = AppHospitalsDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppHospitalsRoute,
} as any)
const AppHospitalsBedsRoute = AppHospitalsBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AppHospitalsRoute,
} as any)
const AppDoctorsAvailabilityRoute = AppDoctorsAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppDoctorsRoute,
} as any)
const AppDoctorsAssignmentsRoute = AppDoctorsAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppDoctorsRoute,
} as any)
const AppBillingIdRoute = AppBillingIdRouteImport.update({
  id: '/billing_/$id',
  path: '/billing/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingPaymentsRoute = AppBillingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppAppointmentsBookingRoute = AppAppointmentsBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AppAppointmentsRoute,
} as any)
const AppAdmissionsDischargeRoute = AppAdmissionsDischargeRouteImport.update({
  id: '/discharge',
  path: '/discharge',
  getParentRoute: () => AppAdmissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admissions': typeof AppAdmissionsRouteWithChildren
  '/appointments': typeof AppAppointmentsRouteWithChildren
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/doctors': typeof AppDoctorsRouteWithChildren
  '/hospitals': typeof AppHospitalsRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/lab': typeof AppLabRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRouteWithChildren
  '/pharmacy': typeof AppPharmacyRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/staff': typeof AppStaffRouteWithChildren
  '/admissions/discharge': typeof AppAdmissionsDischargeRoute
  '/appointments/booking': typeof AppAppointmentsBookingRoute
  '/billing/payments': typeof AppBillingPaymentsRoute
  '/billing/$id': typeof AppBillingIdRoute
  '/doctors/assignments': typeof AppDoctorsAssignmentsRoute
  '/doctors/availability': typeof AppDoctorsAvailabilityRoute
  '/hospitals/beds': typeof AppHospitalsBedsRoute
  '/hospitals/departments': typeof AppHospitalsDepartmentsRoute
  '/hospitals/$id': typeof AppHospitalsIdRoute
  '/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/lab/results': typeof AppLabResultsRoute
  '/lab/samples': typeof AppLabSamplesRoute
  '/patients/registration': typeof AppPatientsRegistrationRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/pharmacy/dispense': typeof AppPharmacyDispenseRoute
  '/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/staff/attendance': typeof AppStaffAttendanceRoute
  '/staff/create': typeof AppStaffCreateRoute
  '/staff/leaves': typeof AppStaffLeavesRoute
  '/staff/payroll': typeof AppStaffPayrollRoute
  '/staff/schedule': typeof AppStaffScheduleRoute
  '/admissions/': typeof AppAdmissionsIndexRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/billing/': typeof AppBillingIndexRoute
  '/doctors/': typeof AppDoctorsIndexRoute
  '/hospitals/': typeof AppHospitalsIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/lab/': typeof AppLabIndexRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/pharmacy/': typeof AppPharmacyIndexRoute
  '/staff/': typeof AppStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/admissions/discharge': typeof AppAdmissionsDischargeRoute
  '/appointments/booking': typeof AppAppointmentsBookingRoute
  '/billing/payments': typeof AppBillingPaymentsRoute
  '/billing/$id': typeof AppBillingIdRoute
  '/doctors/assignments': typeof AppDoctorsAssignmentsRoute
  '/doctors/availability': typeof AppDoctorsAvailabilityRoute
  '/hospitals/beds': typeof AppHospitalsBedsRoute
  '/hospitals/departments': typeof AppHospitalsDepartmentsRoute
  '/hospitals/$id': typeof AppHospitalsIdRoute
  '/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/lab/results': typeof AppLabResultsRoute
  '/lab/samples': typeof AppLabSamplesRoute
  '/patients/registration': typeof AppPatientsRegistrationRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/pharmacy/dispense': typeof AppPharmacyDispenseRoute
  '/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/staff/attendance': typeof AppStaffAttendanceRoute
  '/staff/create': typeof AppStaffCreateRoute
  '/staff/leaves': typeof AppStaffLeavesRoute
  '/staff/payroll': typeof AppStaffPayrollRoute
  '/staff/schedule': typeof AppStaffScheduleRoute
  '/admissions': typeof AppAdmissionsIndexRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/billing': typeof AppBillingIndexRoute
  '/doctors': typeof AppDoctorsIndexRoute
  '/hospitals': typeof AppHospitalsIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/lab': typeof AppLabIndexRoute
  '/patients': typeof AppPatientsIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
  '/staff': typeof AppStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admissions': typeof AppAdmissionsRouteWithChildren
  '/_app/appointments': typeof AppAppointmentsRouteWithChildren
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/doctors': typeof AppDoctorsRouteWithChildren
  '/_app/hospitals': typeof AppHospitalsRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/lab': typeof AppLabRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRouteWithChildren
  '/_app/pharmacy': typeof AppPharmacyRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/staff': typeof AppStaffRouteWithChildren
  '/_app/admissions/discharge': typeof AppAdmissionsDischargeRoute
  '/_app/appointments/booking': typeof AppAppointmentsBookingRoute
  '/_app/billing/payments': typeof AppBillingPaymentsRoute
  '/_app/billing_/$id': typeof AppBillingIdRoute
  '/_app/doctors/assignments': typeof AppDoctorsAssignmentsRoute
  '/_app/doctors/availability': typeof AppDoctorsAvailabilityRoute
  '/_app/hospitals/beds': typeof AppHospitalsBedsRoute
  '/_app/hospitals/departments': typeof AppHospitalsDepartmentsRoute
  '/_app/hospitals_/$id': typeof AppHospitalsIdRoute
  '/_app/inventory/purchases': typeof AppInventoryPurchasesRoute
  '/_app/lab/results': typeof AppLabResultsRoute
  '/_app/lab/samples': typeof AppLabSamplesRoute
  '/_app/patients/registration': typeof AppPatientsRegistrationRoute
  '/_app/patients_/$id': typeof AppPatientsIdRoute
  '/_app/pharmacy/dispense': typeof AppPharmacyDispenseRoute
  '/_app/pharmacy/purchases': typeof AppPharmacyPurchasesRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/staff/attendance': typeof AppStaffAttendanceRoute
  '/_app/staff/create': typeof AppStaffCreateRoute
  '/_app/staff/leaves': typeof AppStaffLeavesRoute
  '/_app/staff/payroll': typeof AppStaffPayrollRoute
  '/_app/staff/schedule': typeof AppStaffScheduleRoute
  '/_app/admissions/': typeof AppAdmissionsIndexRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/doctors/': typeof AppDoctorsIndexRoute
  '/_app/hospitals/': typeof AppHospitalsIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/lab/': typeof AppLabIndexRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/pharmacy/': typeof AppPharmacyIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admissions'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/doctors'
    | '/hospitals'
    | '/inventory'
    | '/lab'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/admissions/discharge'
    | '/appointments/booking'
    | '/billing/payments'
    | '/billing/$id'
    | '/doctors/assignments'
    | '/doctors/availability'
    | '/hospitals/beds'
    | '/hospitals/departments'
    | '/hospitals/$id'
    | '/inventory/purchases'
    | '/lab/results'
    | '/lab/samples'
    | '/patients/registration'
    | '/patients/$id'
    | '/pharmacy/dispense'
    | '/pharmacy/purchases'
    | '/settings/audit'
    | '/settings/roles'
    | '/settings/users'
    | '/staff/attendance'
    | '/staff/create'
    | '/staff/leaves'
    | '/staff/payroll'
    | '/staff/schedule'
    | '/admissions/'
    | '/appointments/'
    | '/billing/'
    | '/doctors/'
    | '/hospitals/'
    | '/inventory/'
    | '/lab/'
    | '/patients/'
    | '/pharmacy/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/admissions/discharge'
    | '/appointments/booking'
    | '/billing/payments'
    | '/billing/$id'
    | '/doctors/assignments'
    | '/doctors/availability'
    | '/hospitals/beds'
    | '/hospitals/departments'
    | '/hospitals/$id'
    | '/inventory/purchases'
    | '/lab/results'
    | '/lab/samples'
    | '/patients/registration'
    | '/patients/$id'
    | '/pharmacy/dispense'
    | '/pharmacy/purchases'
    | '/settings/audit'
    | '/settings/roles'
    | '/settings/users'
    | '/staff/attendance'
    | '/staff/create'
    | '/staff/leaves'
    | '/staff/payroll'
    | '/staff/schedule'
    | '/admissions'
    | '/appointments'
    | '/billing'
    | '/doctors'
    | '/hospitals'
    | '/inventory'
    | '/lab'
    | '/patients'
    | '/pharmacy'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admissions'
    | '/_app/appointments'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/doctors'
    | '/_app/hospitals'
    | '/_app/inventory'
    | '/_app/lab'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/admissions/discharge'
    | '/_app/appointments/booking'
    | '/_app/billing/payments'
    | '/_app/billing_/$id'
    | '/_app/doctors/assignments'
    | '/_app/doctors/availability'
    | '/_app/hospitals/beds'
    | '/_app/hospitals/departments'
    | '/_app/hospitals_/$id'
    | '/_app/inventory/purchases'
    | '/_app/lab/results'
    | '/_app/lab/samples'
    | '/_app/patients/registration'
    | '/_app/patients_/$id'
    | '/_app/pharmacy/dispense'
    | '/_app/pharmacy/purchases'
    | '/_app/settings/audit'
    | '/_app/settings/roles'
    | '/_app/settings/users'
    | '/_app/staff/attendance'
    | '/_app/staff/create'
    | '/_app/staff/leaves'
    | '/_app/staff/payroll'
    | '/_app/staff/schedule'
    | '/_app/admissions/'
    | '/_app/appointments/'
    | '/_app/billing/'
    | '/_app/doctors/'
    | '/_app/hospitals/'
    | '/_app/inventory/'
    | '/_app/lab/'
    | '/_app/patients/'
    | '/_app/pharmacy/'
    | '/_app/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospitals': {
      id: '/_app/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/pharmacy/': {
      id: '/_app/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AppPharmacyIndexRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/_app/lab/': {
      id: '/_app/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof AppLabIndexRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/hospitals/': {
      id: '/_app/hospitals/'
      path: '/'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof AppHospitalsIndexRouteImport
      parentRoute: typeof AppHospitalsRoute
    }
    '/_app/doctors/': {
      id: '/_app/doctors/'
      path: '/'
      fullPath: '/doctors/'
      preLoaderRoute: typeof AppDoctorsIndexRouteImport
      parentRoute: typeof AppDoctorsRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/admissions/': {
      id: '/_app/admissions/'
      path: '/'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AppAdmissionsIndexRouteImport
      parentRoute: typeof AppAdmissionsRoute
    }
    '/_app/staff/schedule': {
      id: '/_app/staff/schedule'
      path: '/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof AppStaffScheduleRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/payroll': {
      id: '/_app/staff/payroll'
      path: '/payroll'
      fullPath: '/staff/payroll'
      preLoaderRoute: typeof AppStaffPayrollRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/leaves': {
      id: '/_app/staff/leaves'
      path: '/leaves'
      fullPath: '/staff/leaves'
      preLoaderRoute: typeof AppStaffLeavesRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/create': {
      id: '/_app/staff/create'
      path: '/create'
      fullPath: '/staff/create'
      preLoaderRoute: typeof AppStaffCreateRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/staff/attendance': {
      id: '/_app/staff/attendance'
      path: '/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof AppStaffAttendanceRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/pharmacy/purchases': {
      id: '/_app/pharmacy/purchases'
      path: '/purchases'
      fullPath: '/pharmacy/purchases'
      preLoaderRoute: typeof AppPharmacyPurchasesRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/pharmacy/dispense': {
      id: '/_app/pharmacy/dispense'
      path: '/dispense'
      fullPath: '/pharmacy/dispense'
      preLoaderRoute: typeof AppPharmacyDispenseRouteImport
      parentRoute: typeof AppPharmacyRoute
    }
    '/_app/patients_/$id': {
      id: '/_app/patients_/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/registration': {
      id: '/_app/patients/registration'
      path: '/registration'
      fullPath: '/patients/registration'
      preLoaderRoute: typeof AppPatientsRegistrationRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/_app/lab/samples': {
      id: '/_app/lab/samples'
      path: '/samples'
      fullPath: '/lab/samples'
      preLoaderRoute: typeof AppLabSamplesRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/lab/results': {
      id: '/_app/lab/results'
      path: '/results'
      fullPath: '/lab/results'
      preLoaderRoute: typeof AppLabResultsRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/inventory/purchases': {
      id: '/_app/inventory/purchases'
      path: '/purchases'
      fullPath: '/inventory/purchases'
      preLoaderRoute: typeof AppInventoryPurchasesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/hospitals_/$id': {
      id: '/_app/hospitals_/$id'
      path: '/hospitals/$id'
      fullPath: '/hospitals/$id'
      preLoaderRoute: typeof AppHospitalsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospitals/departments': {
      id: '/_app/hospitals/departments'
      path: '/departments'
      fullPath: '/hospitals/departments'
      preLoaderRoute: typeof AppHospitalsDepartmentsRouteImport
      parentRoute: typeof AppHospitalsRoute
    }
    '/_app/hospitals/beds': {
      id: '/_app/hospitals/beds'
      path: '/beds'
      fullPath: '/hospitals/beds'
      preLoaderRoute: typeof AppHospitalsBedsRouteImport
      parentRoute: typeof AppHospitalsRoute
    }
    '/_app/doctors/availability': {
      id: '/_app/doctors/availability'
      path: '/availability'
      fullPath: '/doctors/availability'
      preLoaderRoute: typeof AppDoctorsAvailabilityRouteImport
      parentRoute: typeof AppDoctorsRoute
    }
    '/_app/doctors/assignments': {
      id: '/_app/doctors/assignments'
      path: '/assignments'
      fullPath: '/doctors/assignments'
      preLoaderRoute: typeof AppDoctorsAssignmentsRouteImport
      parentRoute: typeof AppDoctorsRoute
    }
    '/_app/billing_/$id': {
      id: '/_app/billing_/$id'
      path: '/billing/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof AppBillingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/payments': {
      id: '/_app/billing/payments'
      path: '/payments'
      fullPath: '/billing/payments'
      preLoaderRoute: typeof AppBillingPaymentsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/appointments/booking': {
      id: '/_app/appointments/booking'
      path: '/booking'
      fullPath: '/appointments/booking'
      preLoaderRoute: typeof AppAppointmentsBookingRouteImport
      parentRoute: typeof AppAppointmentsRoute
    }
    '/_app/admissions/discharge': {
      id: '/_app/admissions/discharge'
      path: '/discharge'
      fullPath: '/admissions/discharge'
      preLoaderRoute: typeof AppAdmissionsDischargeRouteImport
      parentRoute: typeof AppAdmissionsRoute
    }
  }
}

interface AppAdmissionsRouteChildren {
  AppAdmissionsDischargeRoute: typeof AppAdmissionsDischargeRoute
  AppAdmissionsIndexRoute: typeof AppAdmissionsIndexRoute
}

const AppAdmissionsRouteChildren: AppAdmissionsRouteChildren = {
  AppAdmissionsDischargeRoute: AppAdmissionsDischargeRoute,
  AppAdmissionsIndexRoute: AppAdmissionsIndexRoute,
}

const AppAdmissionsRouteWithChildren = AppAdmissionsRoute._addFileChildren(
  AppAdmissionsRouteChildren,
)

interface AppAppointmentsRouteChildren {
  AppAppointmentsBookingRoute: typeof AppAppointmentsBookingRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
}

const AppAppointmentsRouteChildren: AppAppointmentsRouteChildren = {
  AppAppointmentsBookingRoute: AppAppointmentsBookingRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
}

const AppAppointmentsRouteWithChildren = AppAppointmentsRoute._addFileChildren(
  AppAppointmentsRouteChildren,
)

interface AppBillingRouteChildren {
  AppBillingPaymentsRoute: typeof AppBillingPaymentsRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingPaymentsRoute: AppBillingPaymentsRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppDoctorsRouteChildren {
  AppDoctorsAssignmentsRoute: typeof AppDoctorsAssignmentsRoute
  AppDoctorsAvailabilityRoute: typeof AppDoctorsAvailabilityRoute
  AppDoctorsIndexRoute: typeof AppDoctorsIndexRoute
}

const AppDoctorsRouteChildren: AppDoctorsRouteChildren = {
  AppDoctorsAssignmentsRoute: AppDoctorsAssignmentsRoute,
  AppDoctorsAvailabilityRoute: AppDoctorsAvailabilityRoute,
  AppDoctorsIndexRoute: AppDoctorsIndexRoute,
}

const AppDoctorsRouteWithChildren = AppDoctorsRoute._addFileChildren(
  AppDoctorsRouteChildren,
)

interface AppHospitalsRouteChildren {
  AppHospitalsBedsRoute: typeof AppHospitalsBedsRoute
  AppHospitalsDepartmentsRoute: typeof AppHospitalsDepartmentsRoute
  AppHospitalsIndexRoute: typeof AppHospitalsIndexRoute
}

const AppHospitalsRouteChildren: AppHospitalsRouteChildren = {
  AppHospitalsBedsRoute: AppHospitalsBedsRoute,
  AppHospitalsDepartmentsRoute: AppHospitalsDepartmentsRoute,
  AppHospitalsIndexRoute: AppHospitalsIndexRoute,
}

const AppHospitalsRouteWithChildren = AppHospitalsRoute._addFileChildren(
  AppHospitalsRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryPurchasesRoute: typeof AppInventoryPurchasesRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryPurchasesRoute: AppInventoryPurchasesRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppLabRouteChildren {
  AppLabResultsRoute: typeof AppLabResultsRoute
  AppLabSamplesRoute: typeof AppLabSamplesRoute
  AppLabIndexRoute: typeof AppLabIndexRoute
}

const AppLabRouteChildren: AppLabRouteChildren = {
  AppLabResultsRoute: AppLabResultsRoute,
  AppLabSamplesRoute: AppLabSamplesRoute,
  AppLabIndexRoute: AppLabIndexRoute,
}

const AppLabRouteWithChildren =
  AppLabRoute._addFileChildren(AppLabRouteChildren)

interface AppPatientsRouteChildren {
  AppPatientsRegistrationRoute: typeof AppPatientsRegistrationRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsRegistrationRoute: AppPatientsRegistrationRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppPharmacyRouteChildren {
  AppPharmacyDispenseRoute: typeof AppPharmacyDispenseRoute
  AppPharmacyPurchasesRoute: typeof AppPharmacyPurchasesRoute
  AppPharmacyIndexRoute: typeof AppPharmacyIndexRoute
}

const AppPharmacyRouteChildren: AppPharmacyRouteChildren = {
  AppPharmacyDispenseRoute: AppPharmacyDispenseRoute,
  AppPharmacyPurchasesRoute: AppPharmacyPurchasesRoute,
  AppPharmacyIndexRoute: AppPharmacyIndexRoute,
}

const AppPharmacyRouteWithChildren = AppPharmacyRoute._addFileChildren(
  AppPharmacyRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppStaffRouteChildren {
  AppStaffAttendanceRoute: typeof AppStaffAttendanceRoute
  AppStaffCreateRoute: typeof AppStaffCreateRoute
  AppStaffLeavesRoute: typeof AppStaffLeavesRoute
  AppStaffPayrollRoute: typeof AppStaffPayrollRoute
  AppStaffScheduleRoute: typeof AppStaffScheduleRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
}

const AppStaffRouteChildren: AppStaffRouteChildren = {
  AppStaffAttendanceRoute: AppStaffAttendanceRoute,
  AppStaffCreateRoute: AppStaffCreateRoute,
  AppStaffLeavesRoute: AppStaffLeavesRoute,
  AppStaffPayrollRoute: AppStaffPayrollRoute,
  AppStaffScheduleRoute: AppStaffScheduleRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
}

const AppStaffRouteWithChildren = AppStaffRoute._addFileChildren(
  AppStaffRouteChildren,
)

interface AppRouteChildren {
  AppAdmissionsRoute: typeof AppAdmissionsRouteWithChildren
  AppAppointmentsRoute: typeof AppAppointmentsRouteWithChildren
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDoctorsRoute: typeof AppDoctorsRouteWithChildren
  AppHospitalsRoute: typeof AppHospitalsRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppLabRoute: typeof AppLabRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppPharmacyRoute: typeof AppPharmacyRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppStaffRoute: typeof AppStaffRouteWithChildren
  AppBillingIdRoute: typeof AppBillingIdRoute
  AppHospitalsIdRoute: typeof AppHospitalsIdRoute
  AppPatientsIdRoute: typeof AppPatientsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionsRoute: AppAdmissionsRouteWithChildren,
  AppAppointmentsRoute: AppAppointmentsRouteWithChildren,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDoctorsRoute: AppDoctorsRouteWithChildren,
  AppHospitalsRoute: AppHospitalsRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppLabRoute: AppLabRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppPharmacyRoute: AppPharmacyRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppStaffRoute: AppStaffRouteWithChildren,
  AppBillingIdRoute: AppBillingIdRoute,
  AppHospitalsIdRoute: AppHospitalsIdRoute,
  AppPatientsIdRoute: AppPatientsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
